name: Run mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install mypy and third party stubs
        run: pip install mypy types-PyYAML types-click types-pkg_resources

      - name: Install lsst dependencies
        run: |
          pip install -r requirements.txt

      - name: Fake a version
        run: |
          echo "__all__ = ['__version__']" > python/astro_metadata_translator/version.py
          echo "__version__ = '0.0.1'" >> python/astro_metadata_translator/version.py

      - name: Run mypy
        run: mypy python
